ALTER TABLE domain.work
    ADD COLUMN IF NOT EXISTS claimnumber varchar(100),
    ADD COLUMN IF NOT EXISTS insurer varchar(100),
    ADD COLUMN IF NOT EXISTS damagetype varchar(40),
    ADD COLUMN IF NOT EXISTS damagestatus varchar(40),
    ADD COLUMN IF NOT EXISTS assignmentofclaimsigned boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS clientpaysvat boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS audatexestimatenumber varchar(100),
    ADD COLUMN IF NOT EXISTS insurernotes text,
    ADD COLUMN IF NOT EXISTS claimhandlername varchar(200),
    ADD COLUMN IF NOT EXISTS claimhandleremail varchar(200),
    ADD COLUMN IF NOT EXISTS claimhandlerphone varchar(50),
    ADD COLUMN IF NOT EXISTS claimreportedon timestamp,
    ADD COLUMN IF NOT EXISTS estimatesenton timestamp,
    ADD COLUMN IF NOT EXISTS insurerdecisionon timestamp,
    ADD COLUMN IF NOT EXISTS supplementpaidon timestamp,
    ADD COLUMN IF NOT EXISTS plannedintakeon timestamp,
    ADD COLUMN IF NOT EXISTS plannedinspectionon timestamp,
    ADD COLUMN IF NOT EXISTS plannedreleaseon timestamp,
    ADD COLUMN IF NOT EXISTS assignmentofclaimsignedon timestamp,
    ADD COLUMN IF NOT EXISTS powerofattorneysigned boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS powerofattorneysignedon timestamp,
    ADD COLUMN IF NOT EXISTS clientvatpercent integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS clientvatamount numeric(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS underpaymentamount numeric(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS settlementstatus varchar(40) NOT NULL DEFAULT 'unsettled',
    ADD COLUMN IF NOT EXISTS paymentdemandon timestamp,
    ADD COLUMN IF NOT EXISTS paymentreceivedon timestamp,
    ADD COLUMN IF NOT EXISTS settlementnotes text,
    ADD COLUMN IF NOT EXISTS estimatesystem varchar(40),
    ADD COLUMN IF NOT EXISTS estimateversion varchar(50),
    ADD COLUMN IF NOT EXISTS estimatepreparedon timestamp,
    ADD COLUMN IF NOT EXISTS estimatenetamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS estimatevatamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS estimategrossamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS estimatelabormechanicalrbg numeric(12, 2),
    ADD COLUMN IF NOT EXISTS estimatelaborpaintrbg numeric(12, 2),
    ADD COLUMN IF NOT EXISTS estimatestatus varchar(40),
    ADD COLUMN IF NOT EXISTS estimateacceptedon timestamp,
    ADD COLUMN IF NOT EXISTS estimatenotes text,
    ADD COLUMN IF NOT EXISTS invoicenetamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS invoicevatamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS invoicegrossamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS insurerpaidamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS clientsurchargeamount numeric(12, 2),
    ADD COLUMN IF NOT EXISTS paymentdueon timestamp,
    ADD COLUMN IF NOT EXISTS invoicepaymenton timestamp,
    ADD COLUMN IF NOT EXISTS invoicepaymentstatus varchar(40),
    ADD COLUMN IF NOT EXISTS externalinvoiceid varchar(200),
    ADD COLUMN IF NOT EXISTS externalinvoicenumber varchar(100),
    ADD COLUMN IF NOT EXISTS invoicesourcesystem varchar(40);
